# Use redis adapter on all environments because ActionCable doesn't work with async adapter.
# https://github.com/rails/rails/issues/36697

development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: boilerplate_development

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: boilerplate_production
